import {
  faBullhorn,
  faChartLine,
  faCircleCheck,
  faFileExport,
  faGaugeHigh,
  faGear,
  faHeadset,
  faPhotoFilm,
  faMagicWandSparkles,
  faRobot,
  faStar,
  faStore,
  faUserTie,
  faUsers,
  faWallet,
} from '@fortawesome/free-solid-svg-icons';

export const adminNavItems = [
  {
    path: 'overview',
    to: '/dashboard/overview',
    label: 'Ringkasan',
    icon: faGaugeHigh,
    title: 'Ringkasan Platform',
    description: 'Pantau kondisi utama platform dari sisi pengguna, campaign, pembayaran, dan kualitas layanan.',
  },
  {
    path: 'users',
    to: '/dashboard/users',
    label: 'User',
    icon: faUsers,
    title: 'Manajemen User',
    description: 'Kelola akun admin, UMKM, dan influencer dari satu tempat.',
  },
  {
    path: 'influencers',
    to: '/dashboard/influencers',
    label: 'Influencer',
    icon: faUserTie,
    title: 'Manajemen Influencer',
    description: 'Tinjau profil kreator, status verifikasi, portfolio, paket harga, dan performa reputasi.',
  },
  {
    path: 'smes',
    to: '/dashboard/smes',
    label: 'UMKM',
    icon: faStore,
    title: 'Manajemen UMKM',
    description: 'Pantau profil bisnis, aktivitas campaign, dan kebutuhan operasional UMKM.',
  },
  {
    path: 'campaigns',
    to: '/dashboard/campaigns',
    label: 'Campaign',
    icon: faBullhorn,
    title: 'Monitoring Campaign',
    description: 'Awasi seluruh campaign dari tahap pending, aktif, selesai, sampai bermasalah.',
  },
  {
    path: 'payments',
    to: '/dashboard/payments',
    label: 'Pembayaran',
    icon: faWallet,
    title: 'Pusat Pembayaran',
    description: 'Pantau transaksi, status pembayaran, campaign belum dibayar, dan estimasi revenue platform.',
  },
  {
    path: 'reviews',
    to: '/dashboard/reviews',
    label: 'Ulasan',
    icon: faStar,
    title: 'Moderasi Ulasan',
    description: 'Tinjau rating, komentar UMKM, balasan influencer, dan sinyal reputasi platform.',
  },
  {
    path: 'verification',
    to: '/dashboard/verification',
    label: 'Verifikasi',
    icon: faCircleCheck,
    title: 'Verifikasi Influencer',
    description: 'Validasi kelengkapan profil, media sosial, portfolio, dan kesiapan influencer menerima campaign.',
  },
  {
    path: 'content-moderation',
    to: '/dashboard/content-moderation',
    label: 'Konten',
    icon: faPhotoFilm,
    title: 'Moderasi Konten Influencer',
    description: 'Tinjau portfolio, paket harga, link sosial, dan konten publik influencer agar marketplace tetap rapi.',
  },
  {
    path: 'ai-monitor',
    to: '/dashboard/ai-monitor',
    label: 'AI Monitor',
    icon: faRobot,
    title: 'Monitor Penggunaan AI',
    description: 'Pantau endpoint AI, health check lokal, konfigurasi production, dan fitur AI yang perlu dicek.',
  },
  {
    path: 'insights',
    to: '/dashboard/insights',
    label: 'Insight',
    icon: faChartLine,
    title: 'Insight Platform',
    description: 'Lihat tren pertumbuhan user, campaign, revenue, rating, dan kategori influencer terpopuler.',
  },
  {
    path: 'reports',
    to: '/dashboard/reports',
    label: 'Laporan',
    icon: faFileExport,
    title: 'Laporan & Export Data',
    description: 'Export data user, influencer, UMKM, campaign, pembayaran, dan review untuk kebutuhan operasional.',
  },
  {
    path: 'support',
    to: '/dashboard/support',
    label: 'Support',
    icon: faHeadset,
    title: 'Support / Dispute Center',
    description: 'Pantau potensi masalah campaign, pembayaran, review, dan komplain antara UMKM dan influencer.',
  },
  {
    path: 'settings',
    to: '/dashboard/settings',
    label: 'Pengaturan',
    icon: faGear,
    title: 'Pengaturan Platform',
    description: 'Kelola preferensi operasional, kategori niche, fee platform, dan konfigurasi dasar layanan.',
  },
];

export const adminQuickActions = [
  {
    to: '/dashboard/users',
    label: 'Kelola User',
    description: 'Cek akun baru, status aktif, dan role pengguna.',
    icon: faUsers,
  },
  {
    to: '/dashboard/verification',
    label: 'Verifikasi Kreator',
    description: 'Prioritaskan influencer yang siap tampil di marketplace.',
    icon: faCircleCheck,
  },
  {
    to: '/dashboard/campaigns',
    label: 'Pantau Campaign',
    description: 'Lihat campaign yang aktif, tertunda, atau perlu tindak lanjut.',
    icon: faBullhorn,
  },
  {
    to: '/dashboard/ai-monitor',
    label: 'Monitor AI',
    description: 'Pastikan fitur AI tetap stabil untuk UMKM dan influencer.',
    icon: faMagicWandSparkles,
  },
  {
    to: '/dashboard/support',
    label: 'Cek Support',
    description: 'Tinjau campaign bermasalah, unpaid, dan review rating rendah.',
    icon: faHeadset,
  },
];

export const adminPageDetails = {
  users: {
    focusItems: ['Daftar semua akun', 'Filter role dan status', 'Aktivitas pendaftaran terbaru'],
    dataSources: ['users', 'influencers'],
    nextSteps: ['Tambah detail drawer profil', 'Tambah audit aktivitas user', 'Tambah aksi status melalui RPC admin'],
  },
  influencers: {
    focusItems: ['Profil kreator', 'Portfolio dan paket harga', 'Rating serta performa campaign'],
    dataSources: ['influencers', 'influencer_portfolio_items', 'influencer_pricing_packages'],
    nextSteps: ['Tambah detail drawer influencer', 'Tambah aksi verifikasi melalui RPC admin', 'Tambah moderasi portfolio dan paket harga'],
  },
  smes: {
    focusItems: ['Profil bisnis', 'Jumlah campaign', 'Riwayat pembayaran dan ulasan'],
    dataSources: ['users', 'orders', 'reviews'],
    nextSteps: ['Tambah detail drawer bisnis', 'Tambah catatan admin per UMKM', 'Tambah export aktivitas campaign'],
  },
  campaigns: {
    focusItems: ['Status campaign', 'Deadline dan nominal', 'Hubungan UMKM dengan influencer'],
    dataSources: ['v_order_details', 'orders'],
    nextSteps: ['Tambah detail drawer campaign', 'Tambah timeline aktivitas order', 'Tambah aksi eskalasi admin'],
  },
  payments: {
    focusItems: ['Pembayaran pending', 'Campaign belum dibayar', 'Estimasi revenue platform'],
    dataSources: ['orders'],
    nextSteps: ['Tambah aksi update status lewat backend admin', 'Tambah export laporan pembayaran', 'Tambah audit trail transaksi'],
  },
  reviews: {
    focusItems: ['Rating rendah', 'Review terbaru', 'Balasan influencer'],
    dataSources: ['v_influencer_reviews', 'reviews'],
    nextSteps: ['Tambah aksi publikasi lewat backend admin', 'Tambah detail drawer review', 'Tambah eskalasi review rating rendah'],
  },
  verification: {
    focusItems: ['Influencer belum verified', 'Kelengkapan profil', 'Validasi link media sosial'],
    dataSources: ['influencers', 'users', 'influencer_portfolio_items'],
    nextSteps: ['Tambah catatan admin per kreator', 'Tambah riwayat perubahan verifikasi', 'Tambah template alasan profil belum lengkap'],
  },
  'content-moderation': {
    focusItems: ['Portfolio influencer', 'Paket harga publik', 'Issue konten dan link sosial'],
    dataSources: ['influencer_portfolio_items', 'influencer_pricing_packages', 'influencers'],
    nextSteps: ['Tambah aksi hide konten via RPC admin', 'Tambah catatan moderasi', 'Tambah riwayat perubahan konten'],
  },
  'ai-monitor': {
    focusItems: ['Status endpoint AI', 'Health check lokal', 'Konfigurasi env production'],
    dataSources: ['local-api-server', 'edge-functions', 'environment config'],
    nextSteps: ['Tambah log request per fitur', 'Tambah indikator rate limit', 'Tambah histori error production'],
  },
  insights: {
    focusItems: ['Pertumbuhan user', 'Campaign per bulan', 'Kategori influencer paling aktif'],
    dataSources: ['users', 'orders', 'reviews', 'influencer_performance_snapshots'],
    nextSteps: ['Tambah grafik platform', 'Tambah agregasi campaign', 'Tambah insight revenue'],
  },
  reports: {
    focusItems: ['Export CSV', 'Preview dataset', 'Laporan campaign, user, pembayaran, review'],
    dataSources: ['users', 'influencers', 'v_order_details', 'v_influencer_reviews'],
    nextSteps: ['Tambah export PDF', 'Tambah jadwal laporan otomatis', 'Tambah audit download admin'],
  },
  support: {
    focusItems: ['Campaign lewat deadline', 'Pembayaran unpaid', 'Review rating rendah'],
    dataSources: ['v_order_details', 'v_influencer_reviews'],
    nextSteps: ['Tambah tiket support tersimpan', 'Tambah assignment admin', 'Tambah status penyelesaian kasus'],
  },
  settings: {
    focusItems: ['Kategori niche', 'Fee platform', 'Konfigurasi operasional'],
    dataSources: ['platform settings'],
    nextSteps: ['Tambah form pengaturan', 'Tambah validasi admin', 'Tambah audit perubahan'],
  },
};
